apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-custodian
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-job-cc
            image: public.ecr.aws/xxxxxx/test-image-ecr
            imagePullPolicy: Always
            env:
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: AWS_ACCESS_KEY_ID
              value: "XXXXXXXXXXXXXXXX"
            - name: AWS_SECRET_ACCESS_KEY
              value: "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
            command:
            args: ["run","-v","-s","/opt/test","/opt/test/policy.yml"]    
          restartPolicy: OnFailure
